use serde::Deserialize;
use std::collections::HashMap;
use std::env;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::Path;

fn sanitize_identifier(s: &str) -> String {
  s.chars()
    .map(|c| match c {
      'a'..='z' | 'A'..='Z' | '0'..='9' => c,
      _ => '_',
    })
    .collect::<String>()
    .trim_matches('_')
    .to_string()
}

fn escape_string(s: &str) -> String {
  s.replace("\\", "\\\\")
    .replace("\"", "\\\"")
    .replace("\n", "\\n")
    .replace("\r", "\\r")
    .replace("\t", "\\t")
}

#[derive(Deserialize, Debug)]
struct Reporter {
  cite_type: String,
  editions: HashMap<String, Edition>,
  mlz_jurisdiction: Vec<String>,
  name: String,
  variations: HashMap<String, String>,
  #[serde(default)]
  href: Option<String>,
}

#[derive(Deserialize, Debug)]
struct Edition {
  end: Option<String>,
  start: Option<String>,
  #[serde(default)]
  regexes: Option<Vec<String>>,
}

#[derive(Deserialize, Debug)]
struct Journal {
  cite_type: String,
  name: String,
  #[serde(default)]
  start: Option<String>,
  #[serde(default)]
  end: Option<String>,
  #[serde(default)]
  examples: Vec<String>,
  #[serde(default)]
  regexes: Vec<String>,
  #[serde(default)]
  notes: Option<String>,
  #[serde(default)]
  href: Option<String>,
  #[serde(default)]
  #[allow(dead_code)]
  variations: Vec<String>,
}

#[derive(Deserialize, Debug)]
struct Law {
  cite_type: String,
  name: String,
  jurisdiction: String,
  #[serde(default)]
  start: Option<String>,
  #[serde(default)]
  end: Option<String>,
  #[serde(default)]
  examples: Vec<String>,
  #[serde(default)]
  regexes: Vec<String>,
  #[serde(default)]
  notes: Option<String>,
  #[serde(default)]
  href: Option<String>,
  #[serde(default)]
  #[allow(dead_code)]
  variations: Vec<String>,
}

fn main() {
  let out_dir = env::var_os("OUT_DIR").unwrap();
  let dest_path = Path::new(&out_dir).join("generated_data.rs");
  let mut file = BufWriter::new(File::create(&dest_path).unwrap());

  // Generated data follows
  writeln!(file, "// This file is auto-generated by build.rs").unwrap();
  writeln!(file).unwrap();

  // Generate reporters data
  generate_reporters(&mut file);

  // Generate journals data
  generate_journals(&mut file);

  // Generate laws data
  generate_laws(&mut file);

  // Generate state abbreviations
  generate_state_abbreviations(&mut file);

  // Generate case name abbreviations
  generate_case_name_abbreviations(&mut file);

  // Generate regexes
  generate_regexes(&mut file);

  println!("cargo:rerun-if-changed=reporters_db/data/");
}

fn generate_reporters(file: &mut BufWriter<File>) {
  let json = include_str!("reporters_db/data/reporters.json");
  let reporters: HashMap<String, Vec<Reporter>> = serde_json::from_str(json).unwrap();

  // First, generate all the edition maps
  let mut edition_map_names = Vec::new();
  let mut variation_map_names = Vec::new();

  for (key, reporter_list) in &reporters {
    for (idx, reporter) in reporter_list.iter().enumerate() {
      let sanitized_key = sanitize_identifier(key);
      let editions_map_name = format!("EDITIONS_{}_{}", sanitized_key, idx);
      let variations_map_name = format!("VARIATIONS_{}_{}", sanitized_key, idx);

      // Generate editions map
      writeln!(file, "#[allow(non_upper_case_globals)]").unwrap();
      writeln!(
        file,
        "static {}: phf::Map<&'static str, Edition> = ",
        editions_map_name
      )
      .unwrap();
      let mut map = phf_codegen::Map::new();
      for (edition_key, edition) in &reporter.editions {
        let edition_str = format!(
          "Edition {{ end: {}, start: {}, regexes: {} }}",
          edition
            .end
            .as_ref()
            .map(|s| format!("Some(\"{}\")", s))
            .unwrap_or_else(|| "None".to_string()),
          edition
            .start
            .as_ref()
            .map(|s| format!("Some(\"{}\")", s))
            .unwrap_or_else(|| "None".to_string()),
          edition
            .regexes
            .as_ref()
            .map(|v| {
              format!(
                "Some(&[{}])",
                v.iter()
                  .map(|s| format!("\"{}\"", s.replace("\\", "\\\\").replace("\"", "\\\"")))
                  .collect::<Vec<_>>()
                  .join(", ")
              )
            })
            .unwrap_or_else(|| "None".to_string())
        );
        map.entry(edition_key.as_str(), &edition_str);
      }
      writeln!(file, "{};", map.build()).unwrap();
      writeln!(file).unwrap();

      // Generate variations map
      if !reporter.variations.is_empty() {
        writeln!(file, "#[allow(non_upper_case_globals)]").unwrap();
        writeln!(
          file,
          "static {}: phf::Map<&'static str, &'static str> = ",
          variations_map_name
        )
        .unwrap();
        let mut map = phf_codegen::Map::new();
        for (var_key, var_val) in &reporter.variations {
          map.entry(var_key.as_str(), &format!("\"{}\"", var_val));
        }
        writeln!(file, "{};", map.build()).unwrap();
        writeln!(file).unwrap();
        variation_map_names.push(variations_map_name.clone());
      } else {
        variation_map_names.push(String::new());
      }

      edition_map_names.push(editions_map_name);
    }
  }

  // Generate the Reporter struct arrays
  writeln!(file, "#[derive(Debug, Clone)]").unwrap();
  writeln!(file, "pub struct Reporter {{").unwrap();
  writeln!(file, "    pub cite_type: CiteType,").unwrap();
  writeln!(
    file,
    "    pub editions: &'static phf::Map<&'static str, Edition>,"
  )
  .unwrap();
  writeln!(file, "    pub mlz_jurisdiction: &'static [&'static str],").unwrap();
  writeln!(file, "    pub name: &'static str,").unwrap();
  writeln!(
    file,
    "    pub variations: Option<&'static phf::Map<&'static str, &'static str>>,"
  )
  .unwrap();
  writeln!(file, "    pub href: Option<&'static str>,").unwrap();
  writeln!(file, "}}").unwrap();
  writeln!(file).unwrap();

  writeln!(file, "#[derive(Debug, Clone, Copy)]").unwrap();
  writeln!(file, "pub enum CiteType {{").unwrap();
  writeln!(file, "    StateRegional,").unwrap();
  writeln!(file, "    State,").unwrap();
  writeln!(file, "    Federal,").unwrap();
  writeln!(file, "    Specialty,").unwrap();
  writeln!(file, "    Neutral,").unwrap();
  writeln!(file, "    SpecialtyLexis,").unwrap();
  writeln!(file, "    ScotusEarly,").unwrap();
  writeln!(file, "    SpecialtyWest,").unwrap();
  writeln!(file, "}}").unwrap();
  writeln!(file).unwrap();

  writeln!(file, "#[derive(Debug, Clone)]").unwrap();
  writeln!(file, "pub struct Edition {{").unwrap();
  writeln!(file, "    pub end: Option<&'static str>,").unwrap();
  writeln!(file, "    pub start: Option<&'static str>,").unwrap();
  writeln!(file, "    pub regexes: Option<&'static [&'static str]>,").unwrap();
  writeln!(file, "}}").unwrap();
  writeln!(file).unwrap();

  // Generate reporter arrays
  let mut reporter_arrays = Vec::new();
  let mut edition_idx = 0;

  for (key, reporter_list) in &reporters {
    let array_name = format!("REPORTERS_{}", sanitize_identifier(key));

    writeln!(file, "#[allow(non_upper_case_globals)]").unwrap();
    writeln!(file, "static {}: &[Reporter] = &[", array_name).unwrap();
    for reporter in reporter_list {
      let cite_type = match reporter.cite_type.as_str() {
        "state_regional" => "CiteType::StateRegional",
        "state" => "CiteType::State",
        "federal" => "CiteType::Federal",
        "specialty" => "CiteType::Specialty",
        "neutral" => "CiteType::Neutral",
        "specialty_lexis" => "CiteType::SpecialtyLexis",
        "scotus_early" => "CiteType::ScotusEarly",
        "specialty_west" => "CiteType::SpecialtyWest",
        _ => panic!("Unknown cite type: {}", reporter.cite_type),
      };

      let mlz = reporter
        .mlz_jurisdiction
        .iter()
        .map(|s| format!("\"{}\"", escape_string(s)))
        .collect::<Vec<_>>()
        .join(", ");

      let variations = if !variation_map_names[edition_idx].is_empty() {
        format!("Some(&{})", variation_map_names[edition_idx])
      } else {
        "None".to_string()
      };

      writeln!(file, "    Reporter {{").unwrap();
      writeln!(file, "        cite_type: {},", cite_type).unwrap();
      writeln!(
        file,
        "        editions: &{},",
        edition_map_names[edition_idx]
      )
      .unwrap();
      writeln!(file, "        mlz_jurisdiction: &[{}],", mlz).unwrap();
      writeln!(file, "        name: \"{}\",", escape_string(&reporter.name)).unwrap();
      writeln!(file, "        variations: {},", variations).unwrap();
      writeln!(
        file,
        "        href: {},",
        reporter
          .href
          .as_ref()
          .map(|s| format!("Some(\"{}\")", escape_string(s)))
          .unwrap_or_else(|| "None".to_string())
      )
      .unwrap();
      writeln!(file, "    }},").unwrap();

      edition_idx += 1;
    }
    writeln!(file, "];").unwrap();
    writeln!(file).unwrap();

    reporter_arrays.push((key.clone(), array_name));
  }

  // Generate the main REPORTERS map
  writeln!(
    file,
    "pub static REPORTERS: phf::Map<&'static str, &'static [Reporter]> = "
  )
  .unwrap();
  let mut map = phf_codegen::Map::new();
  for (key, array_name) in &reporter_arrays {
    map.entry(key.as_str(), array_name);
  }
  writeln!(file, "{};", map.build()).unwrap();
  writeln!(file).unwrap();
}

fn generate_journals(file: &mut BufWriter<File>) {
  let json = include_str!("reporters_db/data/journals.json");
  let journals: HashMap<String, Vec<Journal>> = serde_json::from_str(json).unwrap();

  writeln!(file, "#[derive(Debug, Clone)]").unwrap();
  writeln!(file, "pub struct Journal {{").unwrap();
  writeln!(file, "    pub cite_type: &'static str,").unwrap();
  writeln!(file, "    pub name: &'static str,").unwrap();
  writeln!(file, "    pub start: Option<&'static str>,").unwrap();
  writeln!(file, "    pub end: Option<&'static str>,").unwrap();
  writeln!(file, "    pub examples: &'static [&'static str],").unwrap();
  writeln!(file, "    pub regexes: &'static [&'static str],").unwrap();
  writeln!(file, "    pub notes: Option<&'static str>,").unwrap();
  writeln!(file, "    pub href: Option<&'static str>,").unwrap();
  writeln!(file, "}}").unwrap();
  writeln!(file).unwrap();

  // Generate journal arrays
  let mut journal_arrays = Vec::new();
  for (key, journal_list) in &journals {
    let array_name = format!("JOURNALS_{}", sanitize_identifier(key));

    writeln!(file, "#[allow(non_upper_case_globals)]").unwrap();
    writeln!(file, "static {}: &[Journal] = &[", array_name).unwrap();
    for journal in journal_list {
      let examples = journal
        .examples
        .iter()
        .map(|s| format!("\"{}\"", escape_string(s)))
        .collect::<Vec<_>>()
        .join(", ");
      let regexes = journal
        .regexes
        .iter()
        .map(|s| format!("\"{}\"", escape_string(s)))
        .collect::<Vec<_>>()
        .join(", ");

      writeln!(file, "    Journal {{").unwrap();
      writeln!(
        file,
        "        cite_type: \"{}\",",
        escape_string(&journal.cite_type)
      )
      .unwrap();
      writeln!(file, "        name: \"{}\",", escape_string(&journal.name)).unwrap();
      writeln!(
        file,
        "        start: {},",
        journal
          .start
          .as_ref()
          .map(|s| format!("Some(\"{}\")", escape_string(s)))
          .unwrap_or_else(|| "None".to_string())
      )
      .unwrap();
      writeln!(
        file,
        "        end: {},",
        journal
          .end
          .as_ref()
          .map(|s| format!("Some(\"{}\")", escape_string(s)))
          .unwrap_or_else(|| "None".to_string())
      )
      .unwrap();
      writeln!(file, "        examples: &[{}],", examples).unwrap();
      writeln!(file, "        regexes: &[{}],", regexes).unwrap();
      writeln!(
        file,
        "        notes: {},",
        journal
          .notes
          .as_ref()
          .map(|s| format!("Some(\"{}\")", escape_string(s)))
          .unwrap_or_else(|| "None".to_string())
      )
      .unwrap();
      writeln!(
        file,
        "        href: {},",
        journal
          .href
          .as_ref()
          .map(|s| format!("Some(\"{}\")", escape_string(s)))
          .unwrap_or_else(|| "None".to_string())
      )
      .unwrap();
      writeln!(file, "    }},").unwrap();
    }
    writeln!(file, "];").unwrap();
    writeln!(file).unwrap();

    journal_arrays.push((key.clone(), array_name));
  }

  // Generate the main JOURNALS map
  writeln!(
    file,
    "pub static JOURNALS: phf::Map<&'static str, &'static [Journal]> = "
  )
  .unwrap();
  let mut map = phf_codegen::Map::new();
  for (key, array_name) in &journal_arrays {
    map.entry(key.as_str(), array_name);
  }
  writeln!(file, "{};", map.build()).unwrap();
  writeln!(file).unwrap();
}

fn generate_laws(file: &mut BufWriter<File>) {
  let json = include_str!("reporters_db/data/laws.json");
  let laws: HashMap<String, Vec<Law>> = serde_json::from_str(json).unwrap();

  writeln!(file, "#[derive(Debug, Clone)]").unwrap();
  writeln!(file, "pub struct Law {{").unwrap();
  writeln!(file, "    pub cite_type: &'static str,").unwrap();
  writeln!(file, "    pub name: &'static str,").unwrap();
  writeln!(file, "    pub jurisdiction: &'static str,").unwrap();
  writeln!(file, "    pub start: Option<&'static str>,").unwrap();
  writeln!(file, "    pub end: Option<&'static str>,").unwrap();
  writeln!(file, "    pub examples: &'static [&'static str],").unwrap();
  writeln!(file, "    pub regexes: &'static [&'static str],").unwrap();
  writeln!(file, "    pub notes: Option<&'static str>,").unwrap();
  writeln!(file, "    pub href: Option<&'static str>,").unwrap();
  writeln!(file, "}}").unwrap();
  writeln!(file).unwrap();

  // Generate law arrays
  let mut law_arrays = Vec::new();
  for (key, law_list) in &laws {
    let array_name = format!("LAWS_{}", sanitize_identifier(key));

    writeln!(file, "#[allow(non_upper_case_globals)]").unwrap();
    writeln!(file, "static {}: &[Law] = &[", array_name).unwrap();
    for law in law_list {
      let examples = law
        .examples
        .iter()
        .map(|s| format!("\"{}\"", escape_string(s)))
        .collect::<Vec<_>>()
        .join(", ");
      let regexes = law
        .regexes
        .iter()
        .map(|s| format!("\"{}\"", escape_string(s)))
        .collect::<Vec<_>>()
        .join(", ");

      writeln!(file, "    Law {{").unwrap();
      writeln!(
        file,
        "        cite_type: \"{}\",",
        escape_string(&law.cite_type)
      )
      .unwrap();
      writeln!(file, "        name: \"{}\",", escape_string(&law.name)).unwrap();
      writeln!(
        file,
        "        jurisdiction: \"{}\",",
        escape_string(&law.jurisdiction)
      )
      .unwrap();
      writeln!(
        file,
        "        start: {},",
        law
          .start
          .as_ref()
          .map(|s| format!("Some(\"{}\")", escape_string(s)))
          .unwrap_or_else(|| "None".to_string())
      )
      .unwrap();
      writeln!(
        file,
        "        end: {},",
        law
          .end
          .as_ref()
          .map(|s| format!("Some(\"{}\")", escape_string(s)))
          .unwrap_or_else(|| "None".to_string())
      )
      .unwrap();
      writeln!(file, "        examples: &[{}],", examples).unwrap();
      writeln!(file, "        regexes: &[{}],", regexes).unwrap();
      writeln!(
        file,
        "        notes: {},",
        law
          .notes
          .as_ref()
          .map(|s| format!("Some(\"{}\")", escape_string(s)))
          .unwrap_or_else(|| "None".to_string())
      )
      .unwrap();
      writeln!(
        file,
        "        href: {},",
        law
          .href
          .as_ref()
          .map(|s| format!("Some(\"{}\")", escape_string(s)))
          .unwrap_or_else(|| "None".to_string())
      )
      .unwrap();
      writeln!(file, "    }},").unwrap();
    }
    writeln!(file, "];").unwrap();
    writeln!(file).unwrap();

    law_arrays.push((key.clone(), array_name));
  }

  // Generate the main LAWS map
  writeln!(
    file,
    "pub static LAWS: phf::Map<&'static str, &'static [Law]> = "
  )
  .unwrap();
  let mut map = phf_codegen::Map::new();
  for (key, array_name) in &law_arrays {
    map.entry(key.as_str(), array_name);
  }
  writeln!(file, "{};", map.build()).unwrap();
  writeln!(file).unwrap();
}

fn generate_state_abbreviations(file: &mut BufWriter<File>) {
  let json = include_str!("reporters_db/data/state_abbreviations.json");
  let abbreviations: HashMap<String, String> = serde_json::from_str(json).unwrap();

  writeln!(
    file,
    "pub static STATE_ABBREVIATIONS: phf::Map<&'static str, &'static str> = "
  )
  .unwrap();
  let mut map = phf_codegen::Map::new();
  for (key, value) in &abbreviations {
    map.entry(key.as_str(), &format!("\"{}\"", escape_string(value)));
  }
  writeln!(file, "{};", map.build()).unwrap();
  writeln!(file).unwrap();
}

fn generate_case_name_abbreviations(file: &mut BufWriter<File>) {
  let json = include_str!("reporters_db/data/case_name_abbreviations.json");
  let abbreviations: HashMap<String, Vec<String>> = serde_json::from_str(json).unwrap();

  writeln!(
    file,
    "pub static CASE_NAME_ABBREVIATIONS: phf::Map<&'static str, &'static [&'static str]> = "
  )
  .unwrap();
  let mut map = phf_codegen::Map::new();
  for (key, values) in &abbreviations {
    let values_str = values
      .iter()
      .map(|s| format!("\"{}\"", escape_string(s)))
      .collect::<Vec<_>>()
      .join(", ");
    map.entry(key.as_str(), &format!("&[{}]", values_str));
  }
  writeln!(file, "{};", map.build()).unwrap();
  writeln!(file).unwrap();
}

fn generate_regexes(file: &mut BufWriter<File>) {
  // For now, keep regexes as runtime-parsed since they need template resolution
  // This is a complex recursive structure that would need more work to fully convert
  writeln!(
    file,
    "// Regexes remain runtime-parsed due to template resolution requirements"
  )
  .unwrap();
  writeln!(file).unwrap();
}
