on:
  pull_request: {}
  push:
    branches:
    - main
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    # Skip Python tests if this is a Rust fork (has Cargo.toml)
    if: ${{ !hashFiles('Cargo.toml') }}
    steps:
    - uses: actions/checkout@v4
    - uses: returntocorp/semgrep-action@v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
